image: openjdk:11

stages: # List of stages for jobs, and their order of execution
  - prepare
  - release

prepare_job:
  stage: prepare # This stage must run before the release stage
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "Downloading required programs..."
    - java -version
    - echo $JAVA_HOME
    - bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
    - bb uberjar dart-cli.jar -m main.core
    #-  bb dart-cli.jar --version > VERSION
    - echo "PRE_JOB_ID=$CI_JOB_ID" >> variables.env
    - echo "TAG=v$(cat VERSION)" >> variables.env # append to the variables.env file
    - echo "Build complete."
  artifacts:
    reports:
      dotenv: variables.env # Use artifacts:reports:dotenv to expose the variables to other jobs
    paths:
      - dart-cli.jar

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:
    name: "Release $TAG"
    description: "Created using the release-cli"
    tag_name: "$TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "Executable $CI_COMMIT_TAG (jar)"
          url: "https://gitlab.com/stindrago/dart-cli/-/jobs/${PRE_JOB_ID}/artifacts/download"
